import type { WallPayload } from "@/lib/database.types";

/** One item as the wall endpoint returns it. The card renders exactly this. */
export type WallItem = WallPayload["testimonials"][number];

/** Clearly-labelled sample data for the styleguide only. */
export const sampleTestimonials: WallItem[] = [
  {
    id: "t1",
    type: "text",
    body: "We sent the link to eleven customers on a Friday and had seven testimonials by Monday. Two of them were video. The old process was me writing awkward follow-up emails for a fortnight.",
    rating: 5,
    video_url: null,
    video_duration_seconds: null,
    poster_url: null,
    author_name: "Priya Raman",
    author_role: "Founder",
    author_company: "Lantern Studio",
    author_avatar_url: null,
  },
  {
    id: "t2",
    type: "video",
    body: "Talks through switching from a Google Form to a proper collection page.",
    rating: 5,
    video_url: null,
    video_duration_seconds: 47,
    poster_url: null,
    author_name: "Marcus Oyelaran",
    author_role: "Head of Growth",
    author_company: "Fieldnote",
    author_avatar_url: null,
  },
  {
    id: "t3",
    type: "text",
    body: "The embed did not fight my site's CSS, which is the first time I can say that about a widget.",
    rating: 5,
    video_url: null,
    video_duration_seconds: null,
    poster_url: null,
    author_name: "Dana Whitfield",
    author_role: "Design lead",
    author_company: "Norrland",
    author_avatar_url: null,
  },
  {
    id: "t4",
    type: "text",
    body: "I record client testimonials at the end of onboarding calls now. One link, they do it on their phone, I approve it that evening. It has quietly become part of the process.",
    rating: 4,
    video_url: null,
    video_duration_seconds: null,
    poster_url: null,
    author_name: "Tomás Herrera",
    author_role: "Independent consultant",
    author_company: null,
    author_avatar_url: null,
  },
  {
    id: "t5",
    type: "text",
    body: "Being able to fix a typo before publishing sounds small. It is not small. Real testimonials arrive messy.",
    rating: 5,
    video_url: null,
    video_duration_seconds: null,
    poster_url: null,
    author_name: "Ana Kowalczyk",
    author_role: "Ops",
    author_company: "Bellwether",
    author_avatar_url: null,
  },
  {
    id: "t6",
    type: "video",
    body: "Ninety seconds on why the video path converts better than a text box.",
    rating: 4,
    video_url: null,
    video_duration_seconds: 82,
    poster_url: null,
    author_name: "Jules Ferrand",
    author_role: "Course creator",
    author_company: null,
    author_avatar_url: null,
  },
  {
    id: "t7",
    type: "text",
    body: "Set up three spaces for three clients in about six minutes. The QR code on the collection page is a nice touch at events.",
    rating: 5,
    video_url: null,
    video_duration_seconds: null,
    poster_url: null,
    author_name: "Sam Okonjo",
    author_role: "Agency owner",
    author_company: "Ninefold",
    author_avatar_url: null,
  },
  {
    id: "t8",
    type: "text",
    body: "Cancelled the $29/mo one. This does the four things I actually used.",
    rating: 5,
    video_url: null,
    video_duration_seconds: null,
    poster_url: null,
    author_name: "Elena Vasquez",
    author_role: "Solo founder",
    author_company: null,
    author_avatar_url: null,
  },
];
